# static_data.py — All embedded geopolitical & infrastructure data
# Converted from worldmonitor-main TypeScript configs
# Sources: IAEA DIIF, ASIAR/HKU, Global Energy Monitor, EIA, public domain

# ============================================================
# NUCLEAR FACILITIES
# ============================================================
NUCLEAR_FACILITIES = [
  # United States
  {"id":"los_alamos","name":"Los Alamos National Laboratory","lat":35.88,"lon":-106.31,"type":"weapons","status":"active"},
  {"id":"sandia","name":"Sandia National Laboratories","lat":35.04,"lon":-106.54,"type":"weapons","status":"active"},
  {"id":"oak_ridge","name":"Oak Ridge National Laboratory","lat":35.93,"lon":-84.31,"type":"enrichment","status":"active"},
  {"id":"savannah_river","name":"Savannah River Site","lat":33.35,"lon":-81.74,"type":"weapons","status":"active"},
  {"id":"pantex","name":"Pantex Plant","lat":35.26,"lon":-101.50,"type":"weapons","status":"active"},
  {"id":"kansas_city","name":"Kansas City Plant","lat":39.03,"lon":-94.57,"type":"weapons","status":"active"},
  {"id":"y12","name":"Y-12 National Security Complex","lat":35.99,"lon":-84.25,"type":"weapons","status":"active"},
  {"id":"nevada_test_site","name":"Nevada National Security Site","lat":37.12,"lon":-116.07,"type":"weapons","status":"inactive"},
  {"id":"hanford","name":"Hanford Site","lat":46.56,"lon":-119.54,"type":"weapons","status":"inactive"},
  {"id":"nnss","name":"NNSS Device Assembly Facility","lat":36.82,"lon":-116.30,"type":"weapons","status":"active"},
  # US Civilian Plants
  {"id":"palo_verde","name":"Palo Verde Nuclear Generating Station","lat":33.39,"lon":-112.86,"type":"plant","status":"active"},
  {"id":"south_texas","name":"South Texas Project","lat":28.80,"lon":-96.05,"type":"plant","status":"active"},
  {"id":"vogtle","name":"Vogtle Electric Generating Plant","lat":33.14,"lon":-81.76,"type":"plant","status":"active"},
  {"id":"browns_ferry","name":"Browns Ferry Nuclear Plant","lat":34.70,"lon":-87.12,"type":"plant","status":"active"},
  {"id":"peach_bottom","name":"Peach Bottom Atomic Power Station","lat":39.75,"lon":-76.27,"type":"plant","status":"active"},
  {"id":"diablo_canyon","name":"Diablo Canyon Power Plant","lat":35.21,"lon":-120.85,"type":"plant","status":"active"},
  # France
  {"id":"tricastin","name":"Tricastin Nuclear Complex","lat":44.33,"lon":4.73,"type":"enrichment","status":"active"},
  {"id":"cadarache","name":"CEA Cadarache","lat":43.69,"lon":5.77,"type":"weapons","status":"active"},
  {"id":"le_bouchet","name":"CEA Le Bouchet","lat":48.48,"lon":2.25,"type":"weapons","status":"inactive"},
  {"id":"flamanville","name":"Flamanville Nuclear Power Plant","lat":49.52,"lon":-1.88,"type":"plant","status":"active"},
  {"id":"gravelines","name":"Gravelines Nuclear Power Plant","lat":51.01,"lon":2.13,"type":"plant","status":"active"},
  # United Kingdom
  {"id":"aldermaston","name":"AWE Aldermaston","lat":51.38,"lon":-1.16,"type":"weapons","status":"active"},
  {"id":"burghfield","name":"AWE Burghfield","lat":51.40,"lon":-1.10,"type":"weapons","status":"active"},
  {"id":"faslane","name":"HMNB Clyde (Faslane)","lat":56.07,"lon":-4.80,"type":"weapons","status":"active"},
  {"id":"sellafield","name":"Sellafield","lat":54.41,"lon":-3.50,"type":"enrichment","status":"active"},
  {"id":"sizewell","name":"Sizewell B","lat":52.21,"lon":1.62,"type":"plant","status":"active"},
  # Russia
  {"id":"sarov","name":"Sarov (Arzamas-16)","lat":54.92,"lon":43.32,"type":"weapons","status":"active"},
  {"id":"snezhinsk","name":"Snezhinsk (Chelyabinsk-70)","lat":56.09,"lon":60.74,"type":"weapons","status":"active"},
  {"id":"trekhgorny","name":"Trekhgorny (Zlatoust-36)","lat":54.82,"lon":58.85,"type":"weapons","status":"active"},
  {"id":"seversk","name":"Seversk (Tomsk-7)","lat":56.60,"lon":84.88,"type":"enrichment","status":"active"},
  {"id":"zheleznogorsk","name":"Zheleznogorsk (Krasnoyarsk-26)","lat":56.25,"lon":93.52,"type":"enrichment","status":"active"},
  {"id":"novouralsk","name":"Novouralsk (Sverdlovsk-44)","lat":57.25,"lon":60.08,"type":"enrichment","status":"active"},
  {"id":"lesnoy","name":"Lesnoy (Sverdlovsk-45)","lat":58.64,"lon":59.79,"type":"weapons","status":"active"},
  {"id":"zarechny","name":"Zarechny (Penza-19)","lat":53.19,"lon":45.18,"type":"weapons","status":"active"},
  {"id":"balakovo","name":"Balakovo Nuclear Power Plant","lat":52.07,"lon":47.87,"type":"plant","status":"active"},
  {"id":"kalininskaya","name":"Kalinin Nuclear Power Plant","lat":57.91,"lon":35.09,"type":"plant","status":"active"},
  {"id":"leningradskaya","name":"Leningrad Nuclear Power Plant","lat":59.87,"lon":29.09,"type":"plant","status":"active"},
  {"id":"kola","name":"Kola Nuclear Power Plant","lat":67.46,"lon":32.46,"type":"plant","status":"active"},
  {"id":"novovoronezhskaya","name":"Novovoronezh Nuclear Power Plant","lat":51.30,"lon":39.22,"type":"plant","status":"active"},
  # Ukraine
  {"id":"zaporizhzhia","name":"Zaporizhzhia Nuclear Power Plant","lat":47.51,"lon":34.59,"type":"plant","status":"contested"},
  {"id":"khmelnytska","name":"Khmelnytska Nuclear Power Plant","lat":50.30,"lon":26.65,"type":"plant","status":"active"},
  {"id":"rivnenska","name":"Rivnenska Nuclear Power Plant","lat":51.37,"lon":25.89,"type":"plant","status":"active"},
  {"id":"pivdennoukrainsk","name":"South Ukraine Nuclear Power Plant","lat":47.83,"lon":31.23,"type":"plant","status":"active"},
  {"id":"chernobyl","name":"Chernobyl Nuclear Power Plant (Exclusion Zone)","lat":51.39,"lon":30.10,"type":"plant","status":"inactive"},
  # China
  {"id":"lop_nor","name":"Lop Nor Nuclear Test Site","lat":40.80,"lon":88.30,"type":"weapons","status":"inactive"},
  {"id":"mianyang","name":"CAEP Mianyang (Jiuzhili)","lat":31.47,"lon":104.79,"type":"weapons","status":"active"},
  {"id":"jiuquan","name":"Jiuquan Atomic Energy Complex","lat":39.87,"lon":100.50,"type":"enrichment","status":"active"},
  {"id":"yumen","name":"Yumen Enrichment Plant","lat":40.21,"lon":97.35,"type":"enrichment","status":"active"},
  {"id":"lanzhou_np","name":"Lanzhou Gaseous Diffusion Plant","lat":36.09,"lon":103.74,"type":"enrichment","status":"active"},
  {"id":"qinshan","name":"Qinshan Nuclear Power Plant","lat":30.44,"lon":120.96,"type":"plant","status":"active"},
  {"id":"daya_bay","name":"Daya Bay Nuclear Power Plant","lat":22.60,"lon":114.54,"type":"plant","status":"active"},
  {"id":"tianwan","name":"Tianwan Nuclear Power Plant","lat":34.70,"lon":119.45,"type":"plant","status":"active"},
  {"id":"haiyang","name":"Haiyang Nuclear Power Plant","lat":36.68,"lon":121.45,"type":"plant","status":"active"},
  {"id":"fuqing","name":"Fuqing Nuclear Power Plant","lat":25.43,"lon":119.39,"type":"plant","status":"active"},
  # Japan
  {"id":"rokkasho","name":"Rokkasho Reprocessing Plant","lat":40.96,"lon":141.35,"type":"enrichment","status":"active"},
  {"id":"tokai","name":"Tokai Research Establishment","lat":36.46,"lon":140.60,"type":"enrichment","status":"active"},
  {"id":"ohi","name":"Oi Nuclear Power Plant","lat":35.53,"lon":135.65,"type":"plant","status":"active"},
  {"id":"sendai_np","name":"Sendai Nuclear Power Plant","lat":31.84,"lon":130.19,"type":"plant","status":"active"},
  {"id":"fukushima_daiichi","name":"Fukushima Daiichi","lat":37.42,"lon":141.03,"type":"plant","status":"inactive"},
  # South Korea
  {"id":"kori","name":"Kori Nuclear Power Plant","lat":35.32,"lon":129.30,"type":"plant","status":"active"},
  {"id":"wolsong","name":"Wolsong Nuclear Power Plant","lat":35.71,"lon":129.47,"type":"plant","status":"active"},
  {"id":"hanul","name":"Hanul Nuclear Power Plant","lat":37.09,"lon":129.38,"type":"plant","status":"active"},
  {"id":"hanbit","name":"Hanbit Nuclear Power Plant","lat":35.41,"lon":126.42,"type":"plant","status":"active"},
  # India
  {"id":"tarapur","name":"Tarapur Atomic Power Station","lat":19.86,"lon":72.71,"type":"plant","status":"active"},
  {"id":"rawatbhata","name":"Rajasthan Atomic Power Station","lat":24.87,"lon":75.59,"type":"plant","status":"active"},
  {"id":"madras","name":"Madras Atomic Power Station","lat":12.42,"lon":80.16,"type":"plant","status":"active"},
  {"id":"narora","name":"Narora Atomic Power Station","lat":28.18,"lon":78.35,"type":"plant","status":"active"},
  {"id":"kaiga","name":"Kaiga Generating Station","lat":14.86,"lon":74.44,"type":"plant","status":"active"},
  {"id":"kudankulam","name":"Kudankulam Nuclear Power Plant","lat":8.17,"lon":77.71,"type":"plant","status":"active"},
  {"id":"barc","name":"Bhabha Atomic Research Centre","lat":19.01,"lon":72.92,"type":"enrichment","status":"active"},
  # Canada
  {"id":"bruce","name":"Bruce Nuclear Generating Station","lat":44.33,"lon":-81.60,"type":"plant","status":"active"},
  {"id":"pickering","name":"Pickering Nuclear Generating Station","lat":43.81,"lon":-79.07,"type":"plant","status":"active"},
  {"id":"darlington","name":"Darlington Nuclear Generating Station","lat":43.87,"lon":-78.72,"type":"plant","status":"active"},
  # Middle East / Contested Programs
  {"id":"natanz","name":"Natanz Fuel Enrichment Plant","lat":33.72,"lon":51.73,"type":"enrichment","status":"active"},
  {"id":"fordow","name":"Fordow Fuel Enrichment Plant","lat":34.88,"lon":50.98,"type":"enrichment","status":"active"},
  {"id":"arak","name":"Arak Heavy Water Reactor","lat":34.55,"lon":49.23,"type":"enrichment","status":"active"},
  {"id":"bushehr","name":"Bushehr Nuclear Power Plant","lat":28.83,"lon":50.89,"type":"plant","status":"active"},
  {"id":"dimona","name":"Negev Nuclear Research Centre (Dimona)","lat":30.86,"lon":35.14,"type":"weapons","status":"active"},
  {"id":"yongbyon","name":"Yongbyon Nuclear Scientific Research Center","lat":39.78,"lon":125.74,"type":"weapons","status":"active"},
  # Pakistan
  {"id":"kahuta","name":"Kahuta Research Laboratories (KRL)","lat":33.59,"lon":73.39,"type":"weapons","status":"active"},
  {"id":"khushab","name":"Khushab Nuclear Complex","lat":32.44,"lon":71.95,"type":"enrichment","status":"active"},
  {"id":"chashma","name":"Chashma Nuclear Power Plants","lat":32.38,"lon":71.46,"type":"plant","status":"active"},
  # Other
  {"id":"bushehr_2","name":"Barakah Nuclear Power Plant","lat":23.95,"lon":52.21,"type":"plant","status":"active"},
  {"id":"cernavoda","name":"Cernavodă Nuclear Power Plant","lat":44.33,"lon":28.06,"type":"plant","status":"active"},
  {"id":"dukovany","name":"Dukovany Nuclear Power Plant","lat":49.09,"lon":16.15,"type":"plant","status":"active"},
  {"id":"temelin","name":"Temelín Nuclear Power Plant","lat":49.19,"lon":14.37,"type":"plant","status":"active"},
  {"id":"mochovce","name":"Mochovce Nuclear Power Plant","lat":48.41,"lon":18.53,"type":"plant","status":"active"},
  {"id":"belene","name":"Belene Nuclear Power Plant","lat":43.63,"lon":25.22,"type":"plant","status":"inactive"},
  {"id":"kozloduy","name":"Kozloduy Nuclear Power Plant","lat":43.80,"lon":23.78,"type":"plant","status":"active"},
]

# ============================================================
# STRATEGIC WATERWAYS
# ============================================================
STRATEGIC_WATERWAYS = [
  {"id":"taiwan_strait","name":"TAIWAN STRAIT","lat":24.0,"lon":119.5,"description":"Critical 180km strait. PLA exercises, USCG transits, 50% of global container fleet."},
  {"id":"malacca","name":"STRAIT OF MALACCA","lat":3.0,"lon":101.5,"description":"World's busiest shipping lane. 80% of E-Asia oil imports. Piracy risk."},
  {"id":"hormuz","name":"STRAIT OF HORMUZ","lat":26.5,"lon":56.5,"description":"21M bpd oil transit. Iranian IRGC harassment. Tanker seizures ongoing."},
  {"id":"bosphorus","name":"BOSPHORUS STRAIT","lat":41.1,"lon":29.0,"description":"Istanbul. Montreux Convention controls warship passage. Russia access point."},
  {"id":"suez","name":"SUEZ CANAL","lat":30.5,"lon":32.3,"description":"12% global trade. Rerouting adds 2 weeks. Houthi attacks shifting traffic."},
  {"id":"panama","name":"PANAMA CANAL","lat":9.1,"lon":-79.7,"description":"3% global trade. Drought restrictions 2023. US built, Panama operates."},
  {"id":"gibraltar","name":"STRAIT OF GIBRALTAR","lat":35.9,"lon":-5.4,"description":"Atlantic-Mediterranean gateway. UK-Spain territorial dispute over Rock."},
  {"id":"bab_el_mandeb","name":"BAB EL-MANDEB","lat":12.5,"lon":43.5,"description":"3.8M bpd oil. Houthi attacks since Nov 2023. US/UK strikes on Yemen targets."},
  {"id":"dardanelles","name":"DARDANELLES","lat":40.2,"lon":26.4,"description":"Turkish strait connecting Aegean to Marmara. NATO-Russia flashpoint."},
]

# ============================================================
# APT GROUPS (Cyber Threat Actors)
# ============================================================
APT_GROUPS = [
  {"id":"apt28","name":"APT28 / Fancy Bear","lat":55.75,"lon":37.6,"actor":"Russia (GRU Unit 26165)","target":"NATO govts, elections","ttps":"Spear-phishing, X-Agent malware","aliases":"Fancy Bear, Strontium, Sofacy"},
  {"id":"apt41","name":"APT41 / Double Dragon","lat":30.6,"lon":104.06,"actor":"China (MSS-linked)","target":"Healthcare, tech, telco","ttps":"Supply chain attacks, ransomware","aliases":"Winnti, Barium, Wicked Panda"},
  {"id":"lazarus","name":"Lazarus Group","lat":39.0,"lon":125.75,"actor":"DPRK (RGB)","target":"Financial, crypto, defense","ttps":"WaterFall, SWIFT attacks, $1.5B crypto stolen","aliases":"Hidden Cobra, Guardians of Peace"},
  {"id":"apt33","name":"APT33 / Charming Kitten","lat":35.7,"lon":51.4,"actor":"Iran (IRGC/MFA)","target":"Energy, aerospace, critical infra","ttps":"Password spray, destructive wiper malware","aliases":"Elfin, Refined Kitten, Peach Sandstorm"},
]

# ============================================================
# CONFLICT ZONES
# ============================================================
CONFLICT_ZONES = [
  {
    "id":"ukraine",
    "name":"Ukraine War",
    "center":[48.0, 31.0],
    "coords":[[52,23],[52,40],[44,40],[44,23]],
    "intensity":"high",
    "parties":["Russia","Ukraine","NATO (support)"],
    "casualties":"500,000+",
    "keywords":["ukraine","russia","zelensky","putin","donbas","kharkiv","kherson","zaporizhzhia","mariupol","bakhmut","drone","missile"],
    "description":"Largest European land war since WWII. Front line stretches 1,200 km."
  },
  {
    "id":"gaza",
    "name":"Gaza War",
    "center":[31.4, 34.4],
    "coords":[[31.6,34.2],[31.6,34.6],[31.2,34.6],[31.2,34.2]],
    "intensity":"high",
    "parties":["Israel (IDF)","Hamas","PIJ","Hezbollah (proxy)"],
    "casualties":"50,000+",
    "keywords":["gaza","hamas","idf","ceasefire","israel","rafah","netanyahu","hostages","west bank"],
    "description":"Hamas Oct 7 attacks triggered IDF ground operation. Humanitarian crisis. 2.2M displaced."
  },
  {
    "id":"sudan",
    "name":"Sudan Civil War",
    "center":[15.5, 32.5],
    "coords":[[23,22],[23,38],[10,38],[10,22]],
    "intensity":"high",
    "parties":["SAF (Sudan Armed Forces)","RSF (Rapid Support Forces)"],
    "casualties":"150,000+",
    "keywords":["sudan","rSF","khartoum","darfur","hemedti","burhan","famine"],
    "description":"SAF vs RSF para-military. 8M+ displaced. Famine declared in Darfur."
  },
  {
    "id":"myanmar",
    "name":"Myanmar Civil War",
    "center":[20.0, 96.0],
    "coords":[[28,92],[28,101],[16,101],[16,92]],
    "intensity":"high",
    "parties":["Military Junta (SAC)","NUG/PDF","MNDAA","TNLA","AA"],
    "casualties":"50,000+",
    "keywords":["myanmar","junta","nug","rohingya","shan","arakan","mandalay","naypyidaw"],
    "description":"Post-coup resistance war. Three Brotherhood Alliance advancing. Junta losing territory."
  },
  {
    "id":"red_sea_yemen",
    "name":"Yemen/Red Sea Crisis",
    "center":[15.5, 44.0],
    "coords":[[18,42],[18,56],[10,56],[10,42]],
    "intensity":"medium",
    "parties":["Houthis (Ansar Allah)","US/UK","Saudi Coalition","UAE"],
    "casualties":"400,000+",
    "keywords":["houthi","yemen","red sea","shipping","tanker","suez","bab el mandeb","missile","drone attack"],
    "description":"Houthi missiles/drones targeting commercial ships since Nov 2023. US/UK strikes ongoing."
  },
  {
    "id":"lebanon",
    "name":"Lebanon War",
    "center":[33.8, 35.8],
    "coords":[[34.7,35.0],[34.7,36.6],[33.0,36.6],[33.0,35.0]],
    "intensity":"medium",
    "parties":["Israel (IDF)","Hezbollah"],
    "casualties":"3,000+",
    "keywords":["lebanon","hezbollah","nasrallah","israel","idf","beirut","south lebanon","pager","walkie talkie"],
    "description":"IDF ground operation in South Lebanon. Nasrallah killed Sep 2024. Hezbollah weakened."
  },
]

# ============================================================
# INTEL HOTSPOTS
# ============================================================
INTEL_HOTSPOTS = [
  {"id":"sahel","name":"Sahel","subtext":"Insurgency/Coups","lat":14.0,"lon":-1.0,"escalationScore":4,"keywords":["burkina faso","mali","niger","sahel","junta","coup","wagner","africa corps"],"description":"Region of instability, military coups, and Islamist insurgency. Russian influence growing."},
  {"id":"haiti","name":"Port-au-Prince","subtext":"Haiti Crisis","lat":18.5,"lon":-72.3,"escalationScore":4,"keywords":["haiti","port-au-prince","gangs","kenya mission"],"description":"Gang violence, government collapse, international security mission."},
  {"id":"horn_africa","name":"Horn of Africa","subtext":"Piracy/Conflict","lat":10.0,"lon":49.0,"escalationScore":4,"keywords":["somalia","piracy","al-shabaab","ethiopia","somaliland","red sea"],"description":"Resurgent piracy, Al-Shabaab activity, Ethiopia-Somaliland port dispute."},
  {"id":"dc","name":"DC","subtext":"Pentagon Pizza Index","lat":38.9,"lon":-77.0,"escalationScore":2,"keywords":["pentagon","white house","congress","cia","nsa","washington","trump"],"description":"US government and military headquarters. Intelligence community center."},
  {"id":"silicon_valley","name":"Silicon Valley","subtext":"Tech/AI Hub","lat":37.4,"lon":-122.1,"escalationScore":1,"keywords":["google","apple","meta","nvidia","openai","ai","artificial intelligence"],"description":"Global tech center. AI development hub."},
  {"id":"moscow","name":"Moscow","subtext":"Kremlin Activity","lat":55.75,"lon":37.6,"escalationScore":4,"keywords":["kremlin","putin","russia","fsb","moscow","russian"],"description":"Russian Federation command center. Military operations hub."},
  {"id":"beijing","name":"Beijing","subtext":"PLA/MSS Activity","lat":39.9,"lon":116.4,"escalationScore":3,"keywords":["beijing","xi","china","pla","ccp","chinese"],"description":"Chinese Communist Party headquarters. PLA command center."},
  {"id":"kyiv","name":"Kyiv","subtext":"Conflict Zone","lat":50.45,"lon":30.5,"escalationScore":5,"keywords":["kyiv","ukraine","zelensky","ukrainian"],"description":"Active conflict zone. NATO support operations."},
  {"id":"taipei","name":"Taipei","subtext":"Strait Watch","lat":25.03,"lon":121.5,"escalationScore":3,"keywords":["taiwan","taipei","tsmc","strait"],"description":"Taiwan Strait tensions. Semiconductor supply chain."},
  {"id":"tehran","name":"Tehran","subtext":"IRGC Activity","lat":35.7,"lon":51.4,"escalationScore":4,"keywords":["iran","tehran","irgc","khamenei","persian"],"description":"Iranian nuclear program. Regional proxy operations."},
  {"id":"telaviv","name":"Tel Aviv","subtext":"Mossad/IDF","lat":32.1,"lon":34.8,"escalationScore":5,"keywords":["israel","idf","mossad","gaza","netanyahu","hamas","hezbollah"],"description":"Military operations. Regional security. Intelligence activities."},
  {"id":"pyongyang","name":"Pyongyang","subtext":"DPRK Watch","lat":39.0,"lon":125.75,"escalationScore":3,"keywords":["north korea","kim","pyongyang","dprk","icbm"],"description":"Nuclear weapons program. Missile testing. Cyber operations."},
  {"id":"london","name":"London","subtext":"GCHQ/MI6","lat":51.5,"lon":-0.12,"escalationScore":2,"keywords":["london","uk","gchq","mi6"],"description":"UK intelligence headquarters. Five Eyes member."},
  {"id":"brussels","name":"Brussels","subtext":"NATO HQ","lat":50.85,"lon":4.35,"escalationScore":2,"keywords":["nato","brussels","eu","european union"],"description":"NATO alliance headquarters. European Union center."},
  {"id":"caracas","name":"Caracas","subtext":"Venezuela Crisis","lat":10.5,"lon":-66.9,"escalationScore":3,"keywords":["venezuela","maduro","caracas"],"description":"Political crisis. Economic sanctions. Regional instability."},
  {"id":"mexico","name":"Mexico City","subtext":"Cartel Violence","lat":23.6,"lon":-102.5,"escalationScore":4,"keywords":["mexico","cartel","sinaloa","fentanyl","narco"],"description":"Cartel warfare, fentanyl trafficking, military deployments."},
  {"id":"nuuk","name":"Nuuk","subtext":"Greenland Intel","lat":64.18,"lon":-51.7,"escalationScore":2,"keywords":["greenland","arctic","denmark"],"description":"Arctic strategic territory. US military presence, sovereignty questions."},
  {"id":"riyadh","name":"Riyadh","subtext":"Saudi GIP/MBS","lat":24.7,"lon":46.7,"escalationScore":2,"keywords":["saudi","riyadh","mbs","aramco","opec"],"description":"Saudi Arabia power center. OPEC+ decisions. Regional influence."},
  {"id":"cairo","name":"Cairo","subtext":"Egypt/GIS","lat":30.0,"lon":31.2,"escalationScore":2,"keywords":["egypt","cairo","sisi","suez"],"description":"Egyptian command. Gaza border control. Suez Canal security."},
  {"id":"baghdad","name":"Baghdad","subtext":"Iraq/PMF","lat":33.3,"lon":44.4,"escalationScore":3,"keywords":["iraq","baghdad","iraqi","pmf","militia"],"description":"Iraqi government. Iran-backed militias. US military presence."},
  {"id":"damascus","name":"Damascus","subtext":"Syria Crisis","lat":33.5,"lon":36.3,"escalationScore":3,"keywords":["syria","damascus","hts"],"description":"Syrian civil war aftermath. Multiple foreign interventions."},
  {"id":"doha","name":"Doha","subtext":"Qatar/Al Udeid","lat":25.3,"lon":51.5,"escalationScore":2,"keywords":["qatar","doha","al udeid","centcom"],"description":"Qatar diplomatic hub. US CENTCOM base. Al Jazeera HQ."},
  {"id":"ankara","name":"Ankara","subtext":"Turkey/MIT","lat":39.9,"lon":32.9,"escalationScore":2,"keywords":["turkey","ankara","erdogan","mit"],"description":"NATO member. Kurdish conflict. Syria/Libya operations."},
  {"id":"beirut","name":"Beirut","subtext":"Lebanon/Hezbollah","lat":33.9,"lon":35.5,"escalationScore":4,"keywords":["lebanon","beirut","hezbollah","nasrallah"],"description":"Lebanon crisis. Hezbollah stronghold. Israel border tensions."},
  {"id":"sanaa","name":"Sana'a","subtext":"Yemen/Houthis","lat":15.4,"lon":44.2,"escalationScore":4,"keywords":["yemen","houthi","red sea"],"description":"Yemen conflict. Houthi Red Sea attacks. Shipping disruption."},
  {"id":"abudhabi","name":"Abu Dhabi","subtext":"UAE/ECSR","lat":24.5,"lon":54.4,"escalationScore":2,"keywords":["uae","abu dhabi","emirates"],"description":"UAE strategic hub. Regional military operations."},
  {"id":"wall_street","name":"Wall Street","subtext":"Financial Hub","lat":40.7,"lon":-74.0,"escalationScore":1,"keywords":["wall street","fed","nyse","nasdaq","dow","sp500","goldman","jpmorgan"],"description":"Global financial center. Market movements. Fed policy."},
  {"id":"houston","name":"Houston","subtext":"Energy/Space","lat":29.76,"lon":-95.37,"escalationScore":1,"keywords":["houston","nasa","spacex","oil","energy","lng"],"description":"Energy sector HQ. NASA mission control. Space industry."},
]

# ============================================================
# MILITARY BASES — Overseas (expanded) + US/NATO
# ============================================================
MILITARY_BASES = [
  # Chinese bases
  {"id":"ream_naval_base","name":"Ream Naval Base","lat":10.44500,"lon":103.63000,"type":"china","country":"Cambodia","arm":"Navy","status":"active","description":"PLA Navy foothold. Deep-water port access. Indian Ocean strategy."},
  {"id":"camp_lemonnier_pla","name":"PLA Support Base Djibouti","lat":11.54360,"lon":43.14860,"type":"china","country":"Djibouti","arm":"Navy","status":"active","description":"China's only acknowledged overseas military base."},
  {"id":"kyaukpyu","name":"Kyaukpyu (Chinese-funded)","lat":19.46000,"lon":93.56000,"type":"china","country":"Myanmar","arm":"Navy","status":"active","description":"Chinese-funded port with dual-use potential."},
  {"id":"pk_tajikistan","name":"PLA Outpost Tajikistan","lat":37.14000,"lon":74.98000,"type":"china","country":"Tajikistan","arm":"Army","status":"active","description":"Border security post. Confirmed PLA presence."},
  {"id":"spratly_fiery","name":"Fiery Cross Reef","lat":9.55000,"lon":112.89000,"type":"china","country":"South China Sea (disputed)","arm":"Navy/Air Force","status":"active","description":"Major artificial island. Airstrip, radar, missile batteries."},
  {"id":"spratly_mischief","name":"Mischief Reef","lat":9.90000,"lon":115.53000,"type":"china","country":"South China Sea (disputed)","arm":"Navy","status":"active","description":"Large military installation. Near Philippines EEZ."},
  {"id":"spratly_subi","name":"Subi Reef","lat":10.92000,"lon":114.08000,"type":"china","country":"South China Sea (disputed)","arm":"Air Force","status":"active","description":"3km runway. Significant military buildup."},
  {"id":"paracel_woody","name":"Woody Island (Yongxing)","lat":16.83000,"lon":112.35000,"type":"china","country":"Paracel Islands (disputed)","arm":"Air Force","status":"active","description":"HQ of Sansha City. Fighter jets, SAM batteries deployed."},
  # French bases
  {"id":"tfk_ndjamena","name":"Forces Françaises au Tchad (N'Djamena)","lat":12.13000,"lon":15.04000,"type":"france","country":"Chad","arm":"Army/Air Force","status":"active","description":"Operation Barkhane successor. French Sahel presence."},
  {"id":"ffd_djibouti","name":"Forces Françaises de Djibouti","lat":11.54900,"lon":43.16000,"type":"france","country":"Djibouti","arm":"Joint","status":"active","description":"Largest permanent French overseas base."},
  {"id":"efao_gabon","name":"Éléments Français au Gabon","lat":0.38600,"lon":9.44500,"type":"france","country":"Gabon","arm":"Army","status":"active","description":"Central Africa force projection base."},
  {"id":"ffg_germany","name":"French Forces Germany","lat":48.98000,"lon":8.40000,"type":"france","country":"Germany","arm":"Army","status":"active","description":"Franco-German brigade. NATO integrated force."},
  {"id":"fci_ivory","name":"Forces françaises en Côte d'Ivoire","lat":5.35000,"lon":-4.00000,"type":"france","country":"Ivory Coast","arm":"Army","status":"active","description":"West Africa logistics hub."},
  {"id":"daman_lebanon","name":"UNIFIL France (Lebanon)","lat":33.26000,"lon":35.20000,"type":"france","country":"Lebanon","arm":"Army","status":"active","description":"UNIFIL peacekeeping force."},
  {"id":"essd_senegal","name":"Éléments Français au Sénégal","lat":14.72000,"lon":-17.44000,"type":"france","country":"Senegal","arm":"Army","status":"active","description":"West Africa military cooperation."},
  {"id":"efau_uae","name":"Abu Dhabi French Military Base","lat":24.43000,"lon":54.65000,"type":"france","country":"UAE","arm":"Joint","status":"active","description":"Port Zayed Naval Base. Joint French UAE."},
  # Indian bases
  {"id":"india_bhutan","name":"India-Bhutan Training Mission","lat":27.47000,"lon":89.64000,"type":"india","country":"Bhutan","arm":"Army","status":"active","description":"Indian Military Training Team (IMTRAT)."},
  {"id":"india_tajik","name":"Farkhor Air Base (India)","lat":37.51000,"lon":68.77000,"type":"india","country":"Tajikistan","arm":"Air Force","status":"active","description":"India's first overseas military base. Afghan border."},
  {"id":"india_oman","name":"Duqm Port (India access)","lat":19.66000,"lon":57.69000,"type":"india","country":"Oman","arm":"Navy","status":"active","description":"Indian Navy access agreement. IOR expansion."},
  {"id":"india_seychelles","name":"Assumption Island (India)","lat":-9.75000,"lon":46.51000,"type":"india","country":"Seychelles","arm":"Navy","status":"active","description":"Indian Ocean surveillance. Contested deal."},
  {"id":"india_maldives","name":"Uthuru Thilafalhu (India)","lat":4.28000,"lon":73.50000,"type":"india","country":"Maldives","arm":"Navy","status":"active","description":"India-Maldives military cooperation post."},
  # Italian bases
  {"id":"it_djibouti","name":"Italian Military Base Djibouti","lat":11.43000,"lon":43.15000,"type":"italy","country":"Djibouti","arm":"Joint","status":"active","description":"Anti-piracy operations. EU NAVFOR support."},
  {"id":"it_kuwait","name":"Italian Forces Kuwait","lat":29.13000,"lon":47.97000,"type":"italy","country":"Kuwait","arm":"Air Force","status":"active","description":"NATO air operations support."},
  {"id":"it_uae","name":"Italian Forces UAE","lat":24.43000,"lon":54.65000,"type":"italy","country":"UAE","arm":"Air Force","status":"active","description":"Italian Air Force detachment."},
  # Russian bases
  {"id":"ru_armenia","name":"102nd Russian Military Base","lat":40.13000,"lon":44.52000,"type":"russia","country":"Armenia","arm":"Army","status":"active","description":"102nd Russian military base. Gyumri."},
  {"id":"ru_belarus","name":"RU-Belarus Joint Training Center","lat":52.09000,"lon":26.10000,"type":"russia","country":"Belarus","arm":"Army","status":"active","description":"Joint military training. Nuclear weapons deployed 2023."},
  {"id":"ru_georgia","name":"CSPR Tskhinvali (S.Ossetia)","lat":42.23000,"lon":43.97000,"type":"russia","country":"Georgia (S. Ossetia)","arm":"Army","status":"active","description":"Russian forces in breakaway S. Ossetia."},
  {"id":"ru_abkhazia","name":"Russian Base Abkhazia","lat":43.00000,"lon":41.02000,"type":"russia","country":"Georgia (Abkhazia)","arm":"Army","status":"active","description":"Russian forces in breakaway Abkhazia."},
  {"id":"ru_kyrgyz","name":"Kant Air Base (Russia)","lat":42.85000,"lon":74.85000,"type":"russia","country":"Kyrgyzstan","arm":"Air Force","status":"active","description":"CSTO air base. CIS integration."},
  {"id":"ru_syria_hmeimim","name":"Hmeimim Air Base","lat":35.40000,"lon":35.95000,"type":"russia","country":"Syria","arm":"Air Force","status":"active","description":"Main Russian air base. Syria operations."},
  {"id":"ru_syria_tartus","name":"Tartus Naval Facility","lat":34.89000,"lon":35.88000,"type":"russia","country":"Syria","arm":"Navy","status":"active","description":"Russia's only Mediterranean naval base."},
  {"id":"ru_tajikistan","name":"201st Russian Military Base","lat":38.58000,"lon":68.78000,"type":"russia","country":"Tajikistan","arm":"Army","status":"active","description":"Russia's largest overseas base."},
  {"id":"ru_venezuela","name":"Russian Military Presence Venezuela","lat":10.20000,"lon":-66.90000,"type":"russia","country":"Venezuela","arm":"Air Force","status":"active","description":"Exercises and logistics. Counterweight to US."},
  # UAE bases
  {"id":"uae_eritrea","name":"UAE Assab Base","lat":13.00000,"lon":42.76000,"type":"uae","country":"Eritrea","arm":"Air Force","status":"active","description":"UAE used for Yemen campaign. Status unclear."},
  {"id":"uae_somaliland","name":"UAE Berbera Base","lat":10.39000,"lon":45.14000,"type":"uae","country":"Somaliland","arm":"Joint","status":"active","description":"Port and airbase. Red Sea/Horn of Africa."},
  # UK bases
  {"id":"baf_falklands","name":"Mount Pleasant Complex","lat":-51.82230,"lon":-58.44720,"type":"uk","country":"Falkland Islands","arm":"Royal Air Force","status":"active","description":"Main British Forces South Atlantic Islands HQ."},
  {"id":"bsb_bahrain","name":"HMS Jufair (Bahrain)","lat":26.20860,"lon":50.57840,"type":"uk","country":"Bahrain","arm":"Royal Navy","status":"active","description":"British Naval Support Facility. Gulf of Bahrain."},
  {"id":"bsb_cyprus","name":"Akrotiri & Dhekelia SBAs","lat":34.59000,"lon":32.99000,"type":"uk","country":"Cyprus","arm":"Royal Air Force","status":"active","description":"Sovereign Base Areas. Middle East operations hub."},
  {"id":"bsb_gibraltar","name":"Gibraltar Garrison","lat":36.14000,"lon":-5.35000,"type":"uk","country":"Gibraltar","arm":"Royal Gibraltar Regiment","status":"active","description":"NATO's Atlantic-Mediterranean gateway."},
  {"id":"bsb_oman","name":"Sultan of Oman's Forces (UK)","lat":23.59770,"lon":58.40590,"type":"uk","country":"Oman","arm":"British Army","status":"active","description":"Training and advisory. Muscat."},
  {"id":"bsb_brune","name":"British Garrison Brunei","lat":4.89000,"lon":114.94000,"type":"uk","country":"Brunei","arm":"British Army","status":"active","description":"Jungle warfare training. Gurkha battalion."},
  {"id":"bsb_singapore","name":"BFBS Singapore","lat":1.31000,"lon":103.80000,"type":"uk","country":"Singapore","arm":"Royal Navy","status":"active","description":"UK-Singapore defence cooperation. Port access."},
  {"id":"bsb_kenya","name":"British Army Training Kenya","lat":-0.36000,"lon":37.59000,"type":"uk","country":"Kenya","arm":"British Army","status":"active","description":"BATUK. Training in Nanyuki highlands."},
  # US/NATO bases
  {"id":"andersen_afb","name":"Andersen Air Force Base","lat":13.57920,"lon":144.92300,"type":"us-nato","country":"Guam","arm":"Air Force","status":"active","description":"Primary US Pacific strategic bomber base."},
  {"id":"robertson_barracks","name":"Robertson Barracks","lat":-12.44000,"lon":130.97000,"type":"us-nato","country":"Australia","arm":"Marines","status":"active","description":"US Marine Rotational Force-Darwin."},
  {"id":"nsa_bahrain","name":"Naval Support Activity Bahrain","lat":26.20860,"lon":50.60970,"type":"us-nato","country":"Bahrain","arm":"Navy","status":"active","description":"5th Fleet HQ."},
  {"id":"camp_lemonnier","name":"Camp Lemonnier","lat":11.54360,"lon":43.14860,"type":"us-nato","country":"Djibouti","arm":"Navy","status":"active","description":"AFRICOM's only permanent base on continent."},
  {"id":"raf_lakenheath","name":"RAF Lakenheath","lat":52.41750,"lon":0.52211,"type":"us-nato","country":"United Kingdom","arm":"Air Force","status":"active","description":"Largest US Air Force base in UK. F-35A jets."},
  {"id":"ramstein","name":"Ramstein Air Base","lat":49.44300,"lon":7.77161,"type":"us-nato","country":"Germany","arm":"Air Force","status":"active","description":"USAFE-AFAFRICA HQ. Primary airlift hub."},
  {"id":"spangdahlem","name":"Spangdahlem Air Base","lat":49.75560,"lon":6.63935,"type":"us-nato","country":"Germany","arm":"Air Force","status":"active","description":"NATO tactical air operations."},
  {"id":"usag_grafenwoehr","name":"USAG Grafenwoehr","lat":49.71730,"lon":11.90640,"type":"us-nato","country":"Germany","arm":"Army","status":"active","description":"Largest US Army training area in Europe."},
  {"id":"usag_stuttgart","name":"USAG Stuttgart","lat":48.78230,"lon":9.17702,"type":"us-nato","country":"Germany","arm":"Army","status":"active","description":"USEUCOM & USAFRICOM headquarters."},
  {"id":"guantanamo","name":"Guantanamo Bay","lat":20.14440,"lon":-75.20920,"type":"us-nato","country":"Cuba","arm":"Navy","status":"active","description":"US Navy base. Detention facility."},
  {"id":"al_udeid","name":"Al Udeid Air Base","lat":25.27930,"lon":51.52240,"type":"us-nato","country":"Qatar","arm":"Air Force","status":"active","description":"CENTCOM Forward HQ. Largest US base in ME."},
  {"id":"prince_sultan_ab","name":"Prince Sultan Air Base","lat":24.07690,"lon":47.56400,"type":"us-nato","country":"Saudi Arabia","arm":"Air Force","status":"active","description":"US Air Force presence in Saudi Arabia."},
  {"id":"al_dhafra_ab","name":"Al Dhafra Air Base","lat":24.24000,"lon":54.55100,"type":"us-nato","country":"UAE","arm":"Air Force","status":"active","description":"F-22 Raptors, ISR aircraft."},
  {"id":"ain_asad","name":"Ain Assad Air Base","lat":33.79860,"lon":42.43910,"type":"us-nato","country":"Iraq","arm":"Army/Air Force","status":"active","description":"US forces remain in Iraq. Iraeli/Iran missile target."},
  {"id":"kadena","name":"Kadena Air Base","lat":26.35450,"lon":127.76600,"type":"us-nato","country":"Japan","arm":"Air Force","status":"active","description":"Largest US air base in Asia. F-15 fighter wing."},
  {"id":"camp_zama","name":"Camp Zama","lat":35.48890,"lon":139.38900,"type":"us-nato","country":"Japan","arm":"Army","status":"active","description":"USARJ HQ. Tokyo area."},
  {"id":"yokota","name":"Yokota Air Base","lat":35.73940,"lon":139.34700,"type":"us-nato","country":"Japan","arm":"Air Force","status":"active","description":"USFJ and PACAF HQ."},
  {"id":"us_army_humphreys","name":"Camp Humphreys","lat":36.96510,"lon":127.03300,"type":"us-nato","country":"South Korea","arm":"Army","status":"active","description":"Largest US overseas military base."},
  {"id":"osan_ab","name":"Osan Air Base","lat":37.09100,"lon":127.03100,"type":"us-nato","country":"South Korea","arm":"Air Force","status":"active","description":"7th Air Force HQ."},
  {"id":"camp_bondsteel","name":"Camp Bondsteel","lat":42.36670,"lon":21.13330,"type":"us-nato","country":"Kosovo","arm":"Army","status":"active","description":"KFOR HQ. Largest US base in SE Europe."},
  {"id":"aviano","name":"Aviano Air Base","lat":46.07060,"lon":12.59470,"type":"us-nato","country":"Italy","arm":"Air Force","status":"active","description":"F-16 fighters. Southern flank NATO."},
  {"id":"naples_nsa","name":"NSA Naples","lat":40.83330,"lon":14.25000,"type":"us-nato","country":"Italy","arm":"Navy","status":"active","description":"US Naval Forces Europe/Africa HQ."},
  {"id":"lajes_field","name":"Lajes Field","lat":38.38330,"lon":-28.26670,"type":"us-nato","country":"Portugal","arm":"Air Force","status":"active","description":"Mid-Atlantic refueling stop. Azores."},
  {"id":"masirah_ab","name":"Masirah Air Base","lat":20.66710,"lon":58.89710,"type":"us-nato","country":"Oman","arm":"Air Force","status":"active","description":"Indian Ocean access. US Air Force."},
  {"id":"camp_arifjan","name":"Camp Arifjan","lat":28.87510,"lon":48.15890,"type":"us-nato","country":"Kuwait","arm":"Army","status":"active","description":"CFLCC HQ. Primary US Army staging area."},
  {"id":"niger_ab201","name":"Niger Air Base 201","lat":16.92120,"lon":8.02595,"type":"us-nato","country":"Niger","arm":"Air Force","status":"active","description":"MQ-9 drone base. Expelled by junta 2024."},
  {"id":"antonio_bautista","name":"Antonio Bautista Air Base","lat":9.74346,"lon":118.76000,"type":"us-nato","country":"Philippines","arm":"Air Force","status":"active","description":"New EDCA base. South China Sea operations."},
  {"id":"fort_magsaysay","name":"Fort Magsaysay","lat":15.43500,"lon":121.09100,"type":"us-nato","country":"Philippines","arm":"Army","status":"active","description":"Largest US training base in Philippines."},
  {"id":"diego_garcia","name":"Diego Garcia","lat":-7.31300,"lon":72.41100,"type":"us-nato","country":"British Indian Ocean Territory","arm":"Navy/Air Force","status":"active","description":"Strategic BIOT base. B-2 bombers operate. Sovereignty contested."},
  # US Domestic
  {"id":"norfolk","name":"Naval Station Norfolk","lat":36.94,"lon":-76.29,"type":"us-domestic","country":"USA","arm":"Navy","status":"active","description":"World's largest naval base. Atlantic Fleet HQ."},
  {"id":"nellis","name":"Nellis Air Force Base","lat":36.24,"lon":-115.03,"type":"us-domestic","country":"USA","arm":"Air Force","status":"active","description":"Fighter weapons school. Red Flag exercises."},
  {"id":"cheyenne","name":"Cheyenne Mountain Complex","lat":38.74,"lon":-104.85,"type":"us-domestic","country":"USA","arm":"NORAD/USSPACECOM","status":"active","description":"NORAD command. Hardened bunker."},
  {"id":"pentagon","name":"The Pentagon","lat":38.87,"lon":-77.06,"type":"us-domestic","country":"USA","arm":"DoD/Joint Chiefs","status":"active","description":"DoD HQ. 23,000 personnel."},
  {"id":"ft_bragg","name":"Fort Liberty (Bragg)","lat":35.14,"lon":-79.00,"type":"us-domestic","country":"USA","arm":"Army/SOCOM","status":"active","description":"Home of 82nd Airborne, Special Forces."},
  {"id":"pearl_harbor","name":"Pearl Harbor-Hickam","lat":21.36,"lon":-157.95,"type":"us-domestic","country":"USA","arm":"Navy/Air Force","status":"active","description":"INDOPACOM HQ. Pacific Fleet."},
  {"id":"ft_hood","name":"Fort Cavazos (Hood)","lat":31.18,"lon":-97.78,"type":"us-domestic","country":"USA","arm":"Army","status":"active","description":"Largest active-duty armored post."},
  {"id":"usaf_peterson","name":"Peterson SFB","lat":38.81,"lon":-104.70,"type":"us-domestic","country":"USA","arm":"Space Force","status":"active","description":"USSPACECOM HQ."},
  {"id":"whiteman","name":"Whiteman AFB","lat":38.72,"lon":-93.55,"type":"us-domestic","country":"USA","arm":"Air Force","status":"active","description":"B-2 Spirit stealth bombers."},
  {"id":"minot","name":"Minot AFB","lat":48.42,"lon":-101.36,"type":"us-domestic","country":"USA","arm":"Air Force","status":"active","description":"B-52 bombers and Minuteman III ICBMs."},
  {"id":"vandenberg","name":"Vandenberg SFB","lat":34.74,"lon":-120.57,"type":"us-domestic","country":"USA","arm":"Space Force","status":"active","description":"ICBM test launches. Space launch."},
  {"id":"portsmouth","name":"Portsmouth Naval Shipyard","lat":43.07,"lon":-70.72,"type":"us-domestic","country":"USA","arm":"Navy","status":"active","description":"Nuclear submarine overhaul."},
  {"id":"westover","name":"Westover ARB","lat":42.20,"lon":-72.53,"type":"us-domestic","country":"USA","arm":"Air Force Reserve","status":"active","description":"C-5 heavy lift transport."},
  {"id":"camp_pendleton","name":"Camp Pendleton","lat":33.37,"lon":-117.56,"type":"us-domestic","country":"USA","arm":"Marines","status":"active","description":"Largest USMC base. Amphibious ops."},
  {"id":"corpus_christi","name":"NAS Corpus Christi","lat":27.69,"lon":-97.29,"type":"us-domestic","country":"USA","arm":"Navy","status":"active","description":"Naval air training command."},
]

# ============================================================
# GAMMA IRRADIATORS (IAEA DIIF Database — 124 facilities)
# ============================================================
GAMMA_IRRADIATORS = [
  {"id":"gi-001","city":"Córdoba","country":"Argentina","lat":-31.4201,"lon":-64.1888},
  {"id":"gi-002","city":"Buenos Aires","country":"Argentina","lat":-34.6037,"lon":-58.3816},
  {"id":"gi-003","city":"Sydney","country":"Australia","lat":-33.8688,"lon":151.2093},
  {"id":"gi-004","city":"Melbourne","country":"Australia","lat":-37.8136,"lon":144.9631},
  {"id":"gi-005","city":"Perth","country":"Australia","lat":-31.9505,"lon":115.8605},
  {"id":"gi-006","city":"Vienna","country":"Austria","lat":48.2082,"lon":16.3738},
  {"id":"gi-007","city":"Minsk","country":"Belarus","lat":53.9045,"lon":27.5615},
  {"id":"gi-008","city":"Ghent","country":"Belgium","lat":51.0543,"lon":3.7174},
  {"id":"gi-009","city":"São Paulo","country":"Brazil","lat":-23.5505,"lon":-46.6333},
  {"id":"gi-010","city":"Rio de Janeiro","country":"Brazil","lat":-22.9068,"lon":-43.1729},
  {"id":"gi-011","city":"Cotia","country":"Brazil","lat":-23.6020,"lon":-46.9189},
  {"id":"gi-012","city":"Sofia","country":"Bulgaria","lat":42.6977,"lon":23.3219},
  {"id":"gi-013","city":"Quebec","country":"Canada","lat":46.8139,"lon":-71.2080},
  {"id":"gi-014","city":"Ontario","country":"Canada","lat":43.7001,"lon":-79.4163},
  {"id":"gi-015","city":"Santiago","country":"Chile","lat":-33.4489,"lon":-70.6693},
  {"id":"gi-016","city":"Beijing","country":"China","lat":39.9042,"lon":116.4074},
  {"id":"gi-017","city":"Shanghai","country":"China","lat":31.2304,"lon":121.4737},
  {"id":"gi-018","city":"Chengdu","country":"China","lat":30.5728,"lon":104.0668},
  {"id":"gi-019","city":"Guangzhou","country":"China","lat":23.1291,"lon":113.2644},
  {"id":"gi-020","city":"Wuhan","country":"China","lat":30.5928,"lon":114.3055},
  {"id":"gi-021","city":"Bogotá","country":"Colombia","lat":4.7110,"lon":-74.0721},
  {"id":"gi-022","city":"Zagreb","country":"Croatia","lat":45.8150,"lon":15.9819},
  {"id":"gi-023","city":"Prague","country":"Czech Republic","lat":50.0755,"lon":14.4378},
  {"id":"gi-024","city":"Olomouc","country":"Czech Republic","lat":49.5938,"lon":17.2509},
  {"id":"gi-025","city":"Cairo","country":"Egypt","lat":30.0444,"lon":31.2357},
  {"id":"gi-026","city":"Helsinki","country":"Finland","lat":60.1699,"lon":24.9384},
  {"id":"gi-027","city":"Paris","country":"France","lat":48.8566,"lon":2.3522},
  {"id":"gi-028","city":"Lyon","country":"France","lat":45.7640,"lon":4.8357},
  {"id":"gi-029","city":"Tbilisi","country":"Georgia","lat":41.6938,"lon":44.8015},
  {"id":"gi-030","city":"Berlin","country":"Germany","lat":52.5200,"lon":13.4050},
  {"id":"gi-031","city":"Munich","country":"Germany","lat":48.1351,"lon":11.5820},
  {"id":"gi-032","city":"Braunschweig","country":"Germany","lat":52.2689,"lon":10.5268},
  {"id":"gi-033","city":"Accra","country":"Ghana","lat":5.6037,"lon":-0.1870},
  {"id":"gi-034","city":"Athens","country":"Greece","lat":37.9838,"lon":23.7275},
  {"id":"gi-035","city":"Guatemala City","country":"Guatemala","lat":14.6349,"lon":-90.5069},
  {"id":"gi-036","city":"Budapest","country":"Hungary","lat":47.4979,"lon":19.0402},
  {"id":"gi-037","city":"Mumbai","country":"India","lat":19.0760,"lon":72.8777},
  {"id":"gi-038","city":"Delhi","country":"India","lat":28.7041,"lon":77.1025},
  {"id":"gi-039","city":"Bangalore","country":"India","lat":12.9716,"lon":77.5946},
  {"id":"gi-040","city":"Hyderabad","country":"India","lat":17.3850,"lon":78.4867},
  {"id":"gi-041","city":"Jakarta","country":"Indonesia","lat":-6.2088,"lon":106.8456},
  {"id":"gi-042","city":"Tehran","country":"Iran","lat":35.6892,"lon":51.3890},
  {"id":"gi-043","city":"Baghdad","country":"Iraq","lat":33.3152,"lon":44.3661},
  {"id":"gi-044","city":"Dublin","country":"Ireland","lat":53.3498,"lon":-6.2603},
  {"id":"gi-045","city":"Tel Aviv","country":"Israel","lat":32.0853,"lon":34.7818},
  {"id":"gi-046","city":"Rome","country":"Italy","lat":41.9028,"lon":12.4964},
  {"id":"gi-047","city":"Milan","country":"Italy","lat":45.4654,"lon":9.1866},
  {"id":"gi-048","city":"Calderara","country":"Italy","lat":44.5636,"lon":11.2381},
  {"id":"gi-049","city":"Osaka","country":"Japan","lat":34.6937,"lon":135.5023},
  {"id":"gi-050","city":"Tokyo","country":"Japan","lat":35.6762,"lon":139.6503},
  {"id":"gi-051","city":"Takasaki","country":"Japan","lat":36.3219,"lon":139.0030},
  {"id":"gi-052","city":"Amman","country":"Jordan","lat":31.9539,"lon":35.9106},
  {"id":"gi-053","city":"Almaty","country":"Kazakhstan","lat":43.2220,"lon":76.8512},
  {"id":"gi-054","city":"Nairobi","country":"Kenya","lat":-1.2921,"lon":36.8219},
  {"id":"gi-055","city":"Pyongyang","country":"DPRK","lat":39.0392,"lon":125.7625},
  {"id":"gi-056","city":"Seoul","country":"South Korea","lat":37.5665,"lon":126.9780},
  {"id":"gi-057","city":"Daejeon","country":"South Korea","lat":36.3504,"lon":127.3845},
  {"id":"gi-058","city":"Riga","country":"Latvia","lat":56.9496,"lon":24.1052},
  {"id":"gi-059","city":"Beirut","country":"Lebanon","lat":33.8938,"lon":35.5018},
  {"id":"gi-060","city":"Kuala Lumpur","country":"Malaysia","lat":3.1390,"lon":101.6869},
  {"id":"gi-061","city":"Petaling Jaya","country":"Malaysia","lat":3.1073,"lon":101.6067},
  {"id":"gi-062","city":"Mexico City","country":"Mexico","lat":19.4326,"lon":-99.1332},
  {"id":"gi-063","city":"Guadalajara","country":"Mexico","lat":20.6597,"lon":-103.3496},
  {"id":"gi-064","city":"Casablanca","country":"Morocco","lat":33.5731,"lon":-7.5898},
  {"id":"gi-065","city":"Amsterdam","country":"Netherlands","lat":52.3676,"lon":4.9041},
  {"id":"gi-066","city":"Wellington","country":"New Zealand","lat":-41.2866,"lon":174.7756},
  {"id":"gi-067","city":"Lagos","country":"Nigeria","lat":6.5244,"lon":3.3792},
  {"id":"gi-068","city":"Abuja","country":"Nigeria","lat":9.0765,"lon":7.3986},
  {"id":"gi-069","city":"Oslo","country":"Norway","lat":59.9139,"lon":10.7522},
  {"id":"gi-070","city":"Karachi","country":"Pakistan","lat":24.8607,"lon":67.0011},
  {"id":"gi-071","city":"Lahore","country":"Pakistan","lat":31.5204,"lon":74.3587},
  {"id":"gi-072","city":"Lima","country":"Peru","lat":-12.0464,"lon":-77.0428},
  {"id":"gi-073","city":"Manila","country":"Philippines","lat":14.5995,"lon":120.9842},
  {"id":"gi-074","city":"Warsaw","country":"Poland","lat":52.2297,"lon":21.0122},
  {"id":"gi-075","city":"Lisbon","country":"Portugal","lat":38.7223,"lon":-9.1393},
  {"id":"gi-076","city":"Bucharest","country":"Romania","lat":44.4268,"lon":26.1025},
  {"id":"gi-077","city":"Obninsk","country":"Russia","lat":55.0951,"lon":36.6123},
  {"id":"gi-078","city":"Moscow","country":"Russia","lat":55.7558,"lon":37.6176},
  {"id":"gi-079","city":"St Petersburg","country":"Russia","lat":59.9343,"lon":30.3351},
  {"id":"gi-080","city":"Novosibirsk","country":"Russia","lat":54.9884,"lon":82.9357},
  {"id":"gi-081","city":"Riyadh","country":"Saudi Arabia","lat":24.6877,"lon":46.7219},
  {"id":"gi-082","city":"Jeddah","country":"Saudi Arabia","lat":21.4858,"lon":39.1925},
  {"id":"gi-083","city":"Belgrade","country":"Serbia","lat":44.8176,"lon":20.4569},
  {"id":"gi-084","city":"Singapore","country":"Singapore","lat":1.3521,"lon":103.8198},
  {"id":"gi-085","city":"Bratislava","country":"Slovakia","lat":48.1486,"lon":17.1077},
  {"id":"gi-086","city":"Cape Town","country":"South Africa","lat":-33.9249,"lon":18.4241},
  {"id":"gi-087","city":"Johannesburg","country":"South Africa","lat":-26.2041,"lon":28.0473},
  {"id":"gi-088","city":"Pelindaba","country":"South Africa","lat":-25.7470,"lon":27.9940},
  {"id":"gi-089","city":"Barcelona","country":"Spain","lat":41.3851,"lon":2.1734},
  {"id":"gi-090","city":"Madrid","country":"Spain","lat":40.4168,"lon":-3.7038},
  {"id":"gi-091","city":"Khartoum","country":"Sudan","lat":15.5007,"lon":32.5599},
  {"id":"gi-092","city":"Stockholm","country":"Sweden","lat":59.3293,"lon":18.0686},
  {"id":"gi-093","city":"Göteborg","country":"Sweden","lat":57.7089,"lon":11.9746},
  {"id":"gi-094","city":"Geneva","country":"Switzerland","lat":46.2044,"lon":6.1432},
  {"id":"gi-095","city":"Zurich","country":"Switzerland","lat":47.3769,"lon":8.5417},
  {"id":"gi-096","city":"Damascus","country":"Syria","lat":33.5138,"lon":36.2765},
  {"id":"gi-097","city":"Taipei","country":"Taiwan","lat":25.0330,"lon":121.5654},
  {"id":"gi-098","city":"Dushanbe","country":"Tajikistan","lat":38.5598,"lon":68.7738},
  {"id":"gi-099","city":"Bangkok","country":"Thailand","lat":13.7563,"lon":100.5018},
  {"id":"gi-100","city":"Pathum Thani","country":"Thailand","lat":14.0208,"lon":100.5250},
  {"id":"gi-101","city":"Tunis","country":"Tunisia","lat":36.8065,"lon":10.1815},
  {"id":"gi-102","city":"Istanbul","country":"Turkey","lat":41.0082,"lon":28.9784},
  {"id":"gi-103","city":"Ankara","country":"Turkey","lat":39.9334,"lon":32.8597},
  {"id":"gi-104","city":"Kyiv","country":"Ukraine","lat":50.4501,"lon":30.5234},
  {"id":"gi-105","city":"Kharkiv","country":"Ukraine","lat":49.9935,"lon":36.2304},
  {"id":"gi-106","city":"Abu Dhabi","country":"UAE","lat":24.4539,"lon":54.3773},
  {"id":"gi-107","city":"Dubai","country":"UAE","lat":25.2048,"lon":55.2708},
  {"id":"gi-108","city":"London","country":"United Kingdom","lat":51.5074,"lon":-0.1278},
  {"id":"gi-109","city":"Didcot","country":"United Kingdom","lat":51.6068,"lon":-1.2429},
  {"id":"gi-110","city":"Chicago","country":"USA","lat":41.8781,"lon":-87.6298},
  {"id":"gi-111","city":"Los Angeles","country":"USA","lat":34.0522,"lon":-118.2437},
  {"id":"gi-112","city":"New York","country":"USA","lat":40.7128,"lon":-74.0060},
  {"id":"gi-113","city":"Atlanta","country":"USA","lat":33.7490,"lon":-84.3880},
  {"id":"gi-114","city":"Houston","country":"USA","lat":29.7604,"lon":-95.3698},
  {"id":"gi-115","city":"Minneapolis","country":"USA","lat":44.9778,"lon":-93.2650},
  {"id":"gi-116","city":"Hanoi","country":"Vietnam","lat":21.0285,"lon":105.8542},
  {"id":"gi-117","city":"Ho Chi Minh City","country":"Vietnam","lat":10.8231,"lon":106.6297},
  {"id":"gi-118","city":"Sana'a","country":"Yemen","lat":15.3694,"lon":44.1910},
  {"id":"gi-119","city":"Lusaka","country":"Zambia","lat":-15.4167,"lon":28.2833},
  {"id":"gi-120","city":"Harare","country":"Zimbabwe","lat":-17.8252,"lon":31.0335},
  {"id":"gi-121","city":"Izmir","country":"Turkey","lat":38.4192,"lon":27.1287},
  {"id":"gi-122","city":"Lima (IPEN)","country":"Peru","lat":-12.0558,"lon":-77.0843},
  {"id":"gi-123","city":"Monterrey","country":"Mexico","lat":25.6866,"lon":-100.3161},
  {"id":"gi-124","city":"Wellington (GNS)","country":"New Zealand","lat":-41.1734,"lon":175.4681},
]

# ============================================================
# PORTS (83 strategic ports)
# ============================================================
PORTS = [
  {"id":"shanghai","name":"Port of Shanghai","lat":31.23,"lon":121.47,"country":"China","type":"container","rank":1,"note":"World's busiest container port. 47M+ TEU."},
  {"id":"singapore","name":"Port of Singapore","lat":1.26,"lon":103.84,"country":"Singapore","type":"mixed","rank":2,"note":"Major transshipment hub. Malacca Strait gateway. 37M+ TEU."},
  {"id":"ningbo","name":"Ningbo-Zhoushan","lat":29.87,"lon":121.55,"country":"China","type":"mixed","rank":3,"note":"Largest cargo throughput globally. 33M+ TEU."},
  {"id":"shenzhen","name":"Port of Shenzhen","lat":22.52,"lon":114.05,"country":"China","type":"container","rank":4,"note":"South China gateway. Yantian terminal. 30M+ TEU."},
  {"id":"guangzhou","name":"Port of Guangzhou","lat":23.08,"lon":113.24,"country":"China","type":"mixed","rank":5,"note":"Pearl River Delta. Nansha terminal. 24M+ TEU."},
  {"id":"qingdao","name":"Port of Qingdao","lat":36.07,"lon":120.31,"country":"China","type":"mixed","rank":6,"note":"North China hub. PLA Navy North Sea Fleet nearby."},
  {"id":"busan","name":"Port of Busan","lat":35.10,"lon":129.04,"country":"South Korea","type":"container","rank":7,"note":"Northeast Asia transshipment hub. 22M+ TEU."},
  {"id":"tianjin","name":"Port of Tianjin","lat":38.99,"lon":117.70,"country":"China","type":"mixed","rank":8,"note":"Beijing's maritime gateway. 21M+ TEU."},
  {"id":"hong_kong","name":"Port of Hong Kong","lat":22.29,"lon":114.15,"country":"China (SAR)","type":"container","rank":9,"note":"Historic transshipment hub. 16M+ TEU."},
  {"id":"rotterdam","name":"Port of Rotterdam","lat":51.90,"lon":4.50,"country":"Netherlands","type":"mixed","rank":10,"note":"Europe's largest port. Gateway to EU. 14M+ TEU."},
  {"id":"jebel_ali","name":"Jebel Ali (Dubai)","lat":25.01,"lon":55.06,"country":"UAE","type":"container","rank":11,"note":"Middle East's largest port. DP World hub. 14M+ TEU."},
  {"id":"antwerp","name":"Port of Antwerp-Bruges","lat":51.26,"lon":4.40,"country":"Belgium","type":"mixed","rank":12,"note":"Europe's second largest. Petrochemicals hub. 13M+ TEU."},
  {"id":"klang","name":"Port Klang","lat":3.00,"lon":101.39,"country":"Malaysia","type":"container","rank":13,"note":"Malacca Strait. Westports terminal. 13M+ TEU."},
  {"id":"xiamen","name":"Port of Xiamen","lat":24.45,"lon":118.08,"country":"China","type":"container","rank":14,"note":"Taiwan Strait. Strategic location. 12M+ TEU."},
  {"id":"kaohsiung","name":"Port of Kaohsiung","lat":22.61,"lon":120.28,"country":"Taiwan","type":"container","rank":15,"note":"Taiwan's largest port. Semiconductor exports."},
  {"id":"los_angeles","name":"Port of Los Angeles","lat":33.73,"lon":-118.26,"country":"USA","type":"container","rank":16,"note":"Western Hemisphere busiest. US-Asia trade gateway."},
  {"id":"long_beach","name":"Port of Long Beach","lat":33.75,"lon":-118.20,"country":"USA","type":"container","rank":17,"note":"Handles 40% of US container imports with LA."},
  {"id":"rotterdam","name":"Port of Rotterdam","lat":51.90,"lon":4.50,"country":"Netherlands","type":"mixed","rank":10,"note":"Europe's largest port."},
  {"id":"hamburg","name":"Port of Hamburg","lat":53.54,"lon":9.99,"country":"Germany","type":"container","rank":19,"note":"Germany's largest. North Sea-Baltic connector."},
  {"id":"new_york_nj","name":"Port of NY/NJ","lat":40.67,"lon":-74.04,"country":"USA","type":"container","rank":21,"note":"US East Coast largest. 9M+ TEU."},
  {"id":"piraeus","name":"Port of Piraeus","lat":37.94,"lon":23.65,"country":"Greece","type":"container","rank":25,"note":"COSCO-operated. China's Mediterranean gateway."},
  {"id":"ras_tanura","name":"Ras Tanura","lat":26.64,"lon":50.16,"country":"Saudi Arabia","type":"oil","note":"World's largest offshore oil terminal. Saudi Aramco. 6.5M+ bpd."},
  {"id":"fujairah","name":"Port of Fujairah","lat":25.12,"lon":56.35,"country":"UAE","type":"oil","note":"Major bunkering hub. Hormuz bypass. Outside Persian Gulf."},
  {"id":"kharg_island","name":"Kharg Island","lat":29.23,"lon":50.31,"country":"Iran","type":"oil","note":"Iran's main oil export terminal. 90%+ of oil exports."},
  {"id":"ras_laffan","name":"Ras Laffan","lat":25.93,"lon":51.54,"country":"Qatar","type":"lng","note":"World's largest LNG export facility. 77M+ tonnes/year."},
  {"id":"houston_port","name":"Port of Houston","lat":29.73,"lon":-95.02,"country":"USA","type":"mixed","note":"US oil/petrochemical hub."},
  {"id":"sabine_pass","name":"Sabine Pass LNG","lat":29.73,"lon":-93.87,"country":"USA","type":"lng","note":"Largest US LNG export terminal. Cheniere Energy."},
  {"id":"novorossiysk","name":"Novorossiysk","lat":44.72,"lon":37.77,"country":"Russia","type":"oil","note":"Russia's largest Black Sea port. CPC terminal."},
  {"id":"primorsk","name":"Primorsk","lat":60.35,"lon":28.62,"country":"Russia","type":"oil","note":"Baltic Sea oil terminal. Russia's largest oil port."},
  {"id":"port_said","name":"Port Said","lat":31.26,"lon":32.30,"country":"Egypt","type":"mixed","note":"Suez Canal northern entrance. 12% of global trade."},
  {"id":"suez_port","name":"Port of Suez","lat":29.97,"lon":32.55,"country":"Egypt","type":"mixed","note":"Suez Canal southern terminus. Red Sea access."},
  {"id":"gibraltar_port","name":"Port of Gibraltar","lat":36.14,"lon":-5.35,"country":"UK","type":"naval","note":"Mediterranean-Atlantic gateway. UK naval base."},
  {"id":"djibouti_port","name":"Port of Djibouti","lat":11.59,"lon":43.15,"country":"Djibouti","type":"mixed","note":"Bab el-Mandeb gateway. Chinese + US military bases."},
  {"id":"aden","name":"Port of Aden","lat":12.79,"lon":45.03,"country":"Yemen","type":"mixed","note":"Red Sea strategic port. Houthi conflict area."},
  {"id":"hodeidah","name":"Port of Hodeidah","lat":14.80,"lon":42.95,"country":"Yemen","type":"bulk","note":"Yemen's main humanitarian port. Houthi-controlled."},
  {"id":"bandar_abbas","name":"Bandar Abbas","lat":27.18,"lon":56.28,"country":"Iran","type":"mixed","note":"Iran's largest container port. Hormuz Strait."},
  {"id":"colon","name":"Port of Colon","lat":9.35,"lon":-79.90,"country":"Panama","type":"container","note":"Panama Canal Atlantic side. Major transshipment."},
  {"id":"balboa","name":"Port of Balboa","lat":8.95,"lon":-79.56,"country":"Panama","type":"container","note":"Panama Canal Pacific terminus. Americas hub."},
  {"id":"algeciras","name":"Port of Algeciras","lat":36.13,"lon":-5.43,"country":"Spain","type":"container","note":"Gibraltar Strait. Maersk transshipment hub."},
  {"id":"zhanjiang","name":"Zhanjiang","lat":21.20,"lon":110.40,"country":"China","type":"naval","note":"PLA Navy South Sea Fleet HQ. Carrier base."},
  {"id":"yulin","name":"Yulin Naval Base","lat":18.23,"lon":109.52,"country":"China","type":"naval","note":"Hainan Island. Nuclear submarine base."},
  {"id":"vladivostok","name":"Port of Vladivostok","lat":43.12,"lon":131.88,"country":"Russia","type":"naval","note":"Russian Pacific Fleet HQ. Trans-Siberian terminus."},
  {"id":"murmansk","name":"Port of Murmansk","lat":68.97,"lon":33.05,"country":"Russia","type":"naval","note":"Arctic ice-free port. Northern Fleet base."},
  {"id":"gwadar","name":"Gwadar","lat":25.12,"lon":62.33,"country":"Pakistan","type":"mixed","note":"Chinese CPEC port. Strategic PLA Navy interest."},
  {"id":"hambantota","name":"Hambantota","lat":6.12,"lon":81.12,"country":"Sri Lanka","type":"mixed","note":"Chinese 99-year lease. Indian Ocean strategic."},
  {"id":"chabahar","name":"Chabahar","lat":25.30,"lon":60.60,"country":"Iran","type":"mixed","note":"India-developed port. Hormuz bypass. Afghanistan access."},
  {"id":"colombo","name":"Port of Colombo","lat":6.94,"lon":79.84,"country":"Sri Lanka","type":"container","note":"Indian Ocean transshipment hub. 7M+ TEU."},
  {"id":"yokohama","name":"Port of Yokohama","lat":35.44,"lon":139.64,"country":"Japan","type":"container","note":"Tokyo Bay. Japan's 2nd largest. US 7th Fleet logistics."},
  {"id":"felixstowe","name":"Port of Felixstowe","lat":51.95,"lon":1.33,"country":"UK","type":"container","note":"UK's busiest container port. 4M+ TEU."},
  {"id":"le_havre","name":"Port of Le Havre","lat":49.48,"lon":0.11,"country":"France","type":"container","note":"France's largest container port. Paris gateway."},
  {"id":"savannah","name":"Port of Savannah","lat":32.08,"lon":-81.09,"country":"USA","type":"container","note":"Fastest growing US port. 5M+ TEU."},
  {"id":"norfolk_port","name":"Port of Virginia","lat":36.95,"lon":-76.33,"country":"USA","type":"mixed","note":"Adjacent to Norfolk Naval Base."},
  {"id":"santos","name":"Port of Santos","lat":-23.95,"lon":-46.30,"country":"Brazil","type":"mixed","note":"Latin America's busiest port. Sao Paulo gateway."},
  {"id":"karachi_port","name":"Port of Karachi","lat":24.84,"lon":67.00,"country":"Pakistan","type":"mixed","note":"Pakistan's largest port. Naval HQ."},
  {"id":"nhava_sheva","name":"Nhava Sheva (JNPT)","lat":18.95,"lon":72.95,"country":"India","type":"container","note":"India's busiest container port. Mumbai gateway."},
  {"id":"chennai_port","name":"Port of Chennai","lat":13.10,"lon":80.29,"country":"India","type":"container","note":"India's 2nd largest. Bay of Bengal."},
  {"id":"mundra","name":"Mundra Port","lat":22.73,"lon":69.72,"country":"India","type":"mixed","note":"India's largest private port. Adani Group."},
]

# ============================================================
# PIPELINES (major oil and gas pipelines)
# ============================================================
PIPELINES = [
  # North America Oil
  {"id":"keystone","name":"Keystone Pipeline","type":"oil","status":"operating","points":[[-104.05,50.95],[-104.0,49.0],[-101.5,46.8],[-97.5,44.4],[-97.0,41.2],[-95.9,36.1],[-95.0,29.8]],"capacity":"590,000 bpd","length":"3,456 km","operator":"TC Energy","countries":["Canada","USA"]},
  {"id":"dakota-access","name":"Dakota Access Pipeline","type":"oil","status":"operating","points":[[-103.5,47.5],[-100.8,46.8],[-97.0,45.5],[-96.0,43.5],[-93.5,41.5],[-91.0,40.5]],"capacity":"570,000 bpd","length":"1,886 km","operator":"Energy Transfer","countries":["USA"]},
  {"id":"trans-mountain","name":"Trans Mountain Pipeline","type":"oil","status":"operating","points":[[-114.1,53.5],[-117.5,52.9],[-119.3,52.1],[-121.0,50.7],[-122.8,49.3]],"capacity":"890,000 bpd","length":"1,150 km","operator":"Trans Mountain Corp","countries":["Canada"]},
  {"id":"colonial","name":"Colonial Pipeline","type":"oil","status":"operating","points":[[-95.4,29.8],[-93.2,30.2],[-90.1,30.0],[-86.8,30.7],[-84.4,33.8],[-80.8,32.1],[-78.6,35.8],[-77.0,38.9],[-74.0,40.7]],"capacity":"2.5 million bpd","length":"8,850 km","operator":"Colonial Pipeline Co","countries":["USA"]},
  {"id":"enbridge-mainline","name":"Enbridge Mainline","type":"oil","status":"operating","points":[[-114.1,53.5],[-110.0,53.5],[-105.0,52.0],[-97.0,49.9],[-92.0,48.0],[-86.0,46.5],[-83.5,42.5]],"capacity":"2.85 million bpd","length":"5,353 km","operator":"Enbridge","countries":["Canada","USA"]},
  {"id":"enbridge-line5","name":"Enbridge Line 5","type":"oil","status":"operating","points":[[-89.0,46.8],[-86.0,45.8],[-84.5,45.5],[-83.0,43.0],[-82.5,42.3]],"capacity":"540,000 bpd","length":"1,038 km","operator":"Enbridge","countries":["USA","Canada"]},
  # Russia/Europe Oil
  {"id":"druzhba","name":"Druzhba Pipeline","type":"oil","status":"operating","points":[[52.3,54.7],[44.0,53.2],[37.6,52.3],[32.0,52.4],[24.0,52.2],[21.0,52.2],[14.4,52.5]],"capacity":"1.2 million bpd","length":"5,327 km","operator":"Transneft","countries":["Russia","Belarus","Poland","Germany","Ukraine","Czech Republic","Hungary"]},
  {"id":"btc","name":"Baku-Tbilisi-Ceyhan (BTC)","type":"oil","status":"operating","points":[[49.9,40.4],[47.5,41.3],[44.8,41.7],[41.6,41.6],[36.8,39.5],[35.9,37.0]],"capacity":"1.2 million bpd","length":"1,768 km","operator":"BP","countries":["Azerbaijan","Georgia","Turkey"]},
  {"id":"cpc","name":"Caspian Pipeline Consortium","type":"oil","status":"operating","points":[[53.0,46.9],[49.0,46.0],[45.5,45.5],[40.0,45.0],[37.4,45.0]],"capacity":"1.4 million bpd","length":"1,510 km","operator":"CPC","countries":["Kazakhstan","Russia"]},
  {"id":"espo","name":"Eastern Siberia-Pacific Ocean (ESPO)","type":"oil","status":"operating","points":[[114.5,56.5],[120.0,55.0],[126.0,52.0],[131.0,48.5],[133.0,47.0]],"capacity":"1.6 million bpd","length":"4,857 km","operator":"Transneft","countries":["Russia"]},
  {"id":"baltic-pipeline","name":"Baltic Pipeline System (BPS)","type":"oil","status":"operating","points":[[50.0,55.0],[40.0,58.0],[32.0,59.5],[28.0,59.9]],"capacity":"1.5 million bpd","length":"2,350 km","operator":"Transneft","countries":["Russia"]},
  # Middle East Oil
  {"id":"east-west","name":"East-West Pipeline (Petroline)","type":"oil","status":"operating","points":[[50.1,26.3],[47.0,26.0],[44.0,25.5],[41.0,24.0],[38.5,22.5]],"capacity":"5 million bpd","length":"1,200 km","operator":"Saudi Aramco","countries":["Saudi Arabia"]},
  {"id":"sumed","name":"SUMED Pipeline","type":"oil","status":"operating","points":[[33.0,29.0],[31.2,30.0],[29.9,31.2]],"capacity":"2.5 million bpd","length":"320 km","operator":"SUMED","countries":["Egypt"]},
  {"id":"kirkuk-ceyhan","name":"Kirkuk-Ceyhan Pipeline","type":"oil","status":"operating","points":[[44.4,35.5],[42.5,36.5],[40.0,37.0],[37.0,37.5],[35.9,37.0]],"capacity":"1.6 million bpd","length":"970 km","operator":"BOTAS/SOMO","countries":["Iraq","Turkey"]},
  {"id":"habshan-fujairah","name":"Habshan-Fujairah Pipeline","type":"oil","status":"operating","points":[[53.6,23.9],[55.0,24.8],[56.2,25.1],[56.4,25.1]],"capacity":"1.5 million bpd","length":"370 km","operator":"ADNOC","countries":["UAE"]},
  # Africa Oil
  {"id":"chad-cameroon","name":"Chad-Cameroon Pipeline","type":"oil","status":"operating","points":[[16.8,10.0],[14.5,7.5],[12.5,5.5],[10.0,4.0]],"capacity":"250,000 bpd","length":"1,070 km","operator":"COTCO","countries":["Chad","Cameroon"]},
  {"id":"nigeria-bonny","name":"Trans-Niger Pipeline (Bonny)","type":"oil","status":"operating","points":[[6.0,5.5],[6.5,5.0],[7.2,4.5]],"capacity":"600,000 bpd","length":"250 km","operator":"Shell","countries":["Nigeria"]},
  {"id":"sudan-port","name":"Greater Nile Oil Pipeline","type":"oil","status":"operating","points":[[30.0,9.5],[32.0,13.0],[34.0,16.0],[37.2,19.6]],"capacity":"500,000 bpd","length":"1,610 km","operator":"GNPOC","countries":["South Sudan","Sudan"]},
  # Asia Oil
  {"id":"china-myanmar","name":"China-Myanmar Pipeline","type":"oil","status":"operating","points":[[93.2,20.1],[96.5,22.0],[98.5,24.0],[100.5,25.0],[102.7,25.0]],"capacity":"440,000 bpd","length":"771 km","operator":"CNPC","countries":["Myanmar","China"]},
  {"id":"kazakhstan-china","name":"Kazakhstan-China Oil Pipeline","type":"oil","status":"operating","points":[[53.0,47.1],[60.0,45.5],[68.0,43.5],[75.0,43.0],[82.0,44.2],[87.6,43.8]],"capacity":"400,000 bpd","length":"2,228 km","operator":"KazTransOil/CNPC","countries":["Kazakhstan","China"]},
  # Russia/Europe Gas
  {"id":"turkstream","name":"TurkStream","type":"gas","status":"operating","points":[[38.5,44.6],[35.0,43.5],[31.0,42.5],[29.0,41.3]],"capacity":"31.5 bcm/year","length":"930 km","operator":"Gazprom","countries":["Russia","Turkey"]},
  {"id":"yamal-europe","name":"Yamal-Europe Pipeline","type":"gas","status":"operating","points":[[73.5,67.5],[66.0,64.0],[55.0,60.0],[45.0,57.0],[32.0,55.0],[24.0,53.0],[17.0,52.5],[14.0,52.5]],"capacity":"33 bcm/year","length":"4,196 km","operator":"Gazprom","countries":["Russia","Belarus","Poland","Germany"]},
  {"id":"trans-adriatic","name":"Trans Adriatic Pipeline (TAP)","type":"gas","status":"operating","points":[[20.1,39.6],[19.5,40.5],[18.0,40.8],[16.5,41.0]],"capacity":"10 bcm/year","length":"878 km","operator":"TAP AG","countries":["Greece","Albania","Italy"]},
  {"id":"tanap","name":"Trans-Anatolian Pipeline (TANAP)","type":"gas","status":"operating","points":[[42.0,41.6],[39.0,40.0],[35.0,39.0],[32.0,38.5],[29.0,39.5],[26.5,40.5]],"capacity":"16 bcm/year","length":"1,850 km","operator":"TANAP","countries":["Azerbaijan","Georgia","Turkey"]},
  {"id":"europipe-i","name":"Europipe I (Norway-Germany)","type":"gas","status":"operating","points":[[2.5,58.5],[4.0,56.0],[6.0,54.5],[8.5,54.0]],"capacity":"18 bcm/year","length":"620 km","operator":"Gassco","countries":["Norway","Germany"]},
  # Middle East Gas
  {"id":"iran-turkey","name":"Iran-Turkey Gas Pipeline","type":"gas","status":"operating","points":[[48.0,38.5],[45.0,38.2],[43.5,37.0],[42.0,37.2]],"capacity":"14 bcm/year","length":"2,577 km","operator":"NIGC/BOTAS","countries":["Iran","Turkey"]},
  {"id":"igat-1","name":"IGAT-1 (Iranian Gas Trunkline)","type":"gas","status":"operating","points":[[52.5,27.5],[51.5,30.5],[50.5,32.5],[48.5,35.5],[48.0,38.0]],"capacity":"15 bcm/year","length":"1,100 km","operator":"NIGC","countries":["Iran"]},
  {"id":"leviathan-ashdod","name":"Leviathan Gas Pipeline","type":"gas","status":"operating","points":[[34.0,33.0],[34.5,32.5],[34.6,31.8]],"capacity":"12 bcm/year","length":"120 km","operator":"Noble Energy","countries":["Israel"]},
]
