import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type, x-supabase-client-platform, x-supabase-client-platform-version, x-supabase-client-runtime, x-supabase-client-runtime-version",
};

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const { action, incident, successRate, details, severity, location } = await req.json();
    const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY");
    if (!RESEND_API_KEY) throw new Error("RESEND_API_KEY not configured");

    const html = `
    <div style="font-family:'Courier New',monospace;background:#0a0e1a;color:#e0e0e0;padding:24px;border-radius:8px;max-width:600px;margin:0 auto">
      <div style="border-bottom:2px solid #ff6600;padding-bottom:12px;margin-bottom:16px">
        <h1 style="color:#ff9933;font-size:18px;margin:0">🛡️ SoTaNik_AI — ACTION DIRECTIVE</h1>
        <p style="color:#666;font-size:11px;margin:4px 0 0">TOP SECRET // INDIA EYES ONLY</p>
      </div>
      
      <div style="background:#111827;border:1px solid #374151;border-radius:6px;padding:16px;margin-bottom:16px">
        <h2 style="color:#ef4444;font-size:14px;margin:0 0 8px">⚠️ INCIDENT</h2>
        <p style="font-size:13px;color:#d1d5db;margin:0">${incident || 'N/A'}</p>
        ${severity ? `<span style="display:inline-block;margin-top:8px;padding:2px 8px;border-radius:4px;font-size:10px;font-weight:bold;background:${severity === 'critical' ? '#7f1d1d' : severity === 'high' ? '#78350f' : '#1e3a5f'};color:${severity === 'critical' ? '#fca5a5' : severity === 'high' ? '#fbbf24' : '#93c5fd'}">${severity.toUpperCase()}</span>` : ''}
        ${location ? `<p style="color:#666;font-size:11px;margin-top:6px">📍 ${location}</p>` : ''}
      </div>

      <div style="background:#0f1f0f;border:1px solid #166534;border-radius:6px;padding:16px;margin-bottom:16px">
        <h2 style="color:#22c55e;font-size:14px;margin:0 0 8px">✅ PROPOSED ACTION</h2>
        <p style="font-size:13px;color:#d1d5db;margin:0">${action || 'N/A'}</p>
        ${successRate ? `<div style="margin-top:12px;padding:8px;background:#052e16;border-radius:4px"><span style="color:#4ade80;font-size:12px;font-weight:bold">SUCCESS PROBABILITY: ${successRate}%</span><div style="background:#1a1a2e;height:8px;border-radius:4px;margin-top:6px;overflow:hidden"><div style="background:linear-gradient(90deg,#22c55e,#4ade80);height:100%;width:${successRate}%;border-radius:4px"></div></div></div>` : ''}
      </div>

      ${details ? `<div style="background:#111827;border:1px solid #374151;border-radius:6px;padding:16px;margin-bottom:16px"><h2 style="color:#60a5fa;font-size:14px;margin:0 0 8px">📋 DETAILS</h2><p style="font-size:12px;color:#9ca3af;margin:0;white-space:pre-wrap">${details}</p></div>` : ''}

      <div style="border-top:1px solid #1f2937;padding-top:12px;text-align:center">
        <p style="color:#4b5563;font-size:10px;margin:0">Generated by SoTaNik_AI Defense Intelligence Platform</p>
        <p style="color:#374151;font-size:9px;margin:4px 0 0">${new Date().toISOString()}</p>
      </div>
    </div>`;

    const res = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: { "Authorization": `Bearer ${RESEND_API_KEY}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        from: "onboarding@resend.dev",
        to: "sagnik.saha.raptor@gmail.com",
        subject: `[SoTaNik_AI] ${severity ? severity.toUpperCase() + ' — ' : ''}${(action || incident || 'Intel Action').slice(0, 80)}`,
        html,
      }),
    });

    const result = await res.json();
    if (!res.ok) throw new Error(result.message || `Resend ${res.status}`);

    console.log("[EMAIL] Sent intel action:", result.id);
    return new Response(JSON.stringify({ success: true, id: result.id }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e: any) {
    console.error("[EMAIL] Error:", e);
    return new Response(JSON.stringify({ error: e.message }), {
      status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  }
});
